### ISSUE TITLE
Already existing media

### ISSUE THREAD

**Issue by fulviods** [johnbillion/network-media-library#30]
Hi
I decided to finally add a second website to a multisite and installed your plugin.
All the media from the first website are not visible anymore neither in the first or second website! , your system works only with new media apparently!

I'm using the plugin enhanced media library (https://wpuxsolutions.com/) but don't think its the problem
Is there a way to access all the old media ?
Thanks

**Comment by johnbillion** [comment]
Hi!

You're right that this plugin is intended for new Multisite networks.

However, you can use the `network-media-library/site_id` filter to change the central media library site to 1 to use the existing media. More details here: https://github.com/johnbillion/network-media-library/blob/master/readme.md#description

John

**Comment by fulviods** [comment]
In fact I realize that there is a bug when I add the function 

`add_filter( 'network-media-library/site_id', function( $site_id ) {
    return 1;
} );

all the admin accounts of the site 1 have a limited dashboard 
They only have access to "Profile" and "Media" section, no more pages,posts,settings,plugins.....
If i avoid to add this function admin can see the dashboard again...but old media are not shared anymore...

Any idea?`

**Comment by johnbillion** [comment]
I think your best approach is to export the media from the original site and import them into a dedicated site.

**Comment by fulviods** [comment]
Sad that it doesnt work
What do you mean by export and import to a dedicated site ?

Actually I have everything in this folder:

/public_html/wp-content/uploads

And inside this folder I have a «sites” folder with the second library for the other site

If i move everything from the root to the 2nd site i’ll loose everything on the first site and i’ll have to place again all the documents in the website…




 

De : John Blackbourn <notifications@github.com> 
Envoyé : mardi, 16 octobre 2018 17:01
À : johnbillion/network-media-library <network-media-library@noreply.github.com>
Cc : fulviods <webmaster@internetdiffusion.com>; Author <author@noreply.github.com>
Objet : Re: [johnbillion/network-media-library] Already existing media (#30)

 

I think your best approach is to export the media from the original site and import them into a dedicated site.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <http://tracking.internetdiffusion.com/tracking/click?d=Qc7VGIU-YEgEC_WCG464y5RXtK2YQgm3uMyd5XY78LNeRG3VGxj0BNfkMJGNBuYcQ1yWvkWzjmONog-ccsrJeauXJBaszdt8oE8jaSg9Tz6Bjd-2eZwkNbDektt0Lykd_5YvvLBzl5q0YQ9KbikhuxOGN0L-YUFCD81RzRJGcp30iwhTnrL-q__cBnwe1jgoJGOsT605WgO12l2p7hk6iw81> , or mute the thread <http://tracking.internetdiffusion.com/tracking/click?d=wHp2_TbnEyUPR2QI4PMd4O-zr2EahVy_XlxCIz-HjtrblL_-brFxBUj4QkczPBzmkGpQLNelS-4ZI8RziFvybEhPK2QizI1KxDPOABnATeeXm2kzzbwgtVPYxneeZf3Q45GdtQaLHHczPkR74vnBglK7ncSic8HDb5SKA7zeOp7l1eWP96uptExgvdHDoQynBwsntghgOAj_o-NhUgllvelmWIYTbptC85Q8UvNkwpBK0> .  <http://tracking.internetdiffusion.com/tracking/click?d=3EeYTvD0AgL5nazvLwGDfPl5MlUR53HovAPEVrWrzPRmJZD7i5Zg2bEOJwSvz4DN-gj4jNhbTIG-LyCNe-B4gXmBI4VIc51B7C9-b415GZ4S6BpEfxAU7mRVyso6ga2JF6W2WuiicJAmyNhWqsjAkuqB8huEgTfQs7yizMr8oTjR49uvDSN507PHqFSPZCaEv2ufQ5uvG-oGLYPX_GeKCDQ1> 

 http://tracking.internetdiffusion.com/tracking/unsubscribe?msgid=TKxVxU-sZVOpuEWwijurvA2

**Comment by fulviods** [comment]
If you can tell me would be nice.
I deactivated your plugin and my client tell me that she lost all the content in the second website (divi theme). I didnt check the website before... it is possible?
Thanks for your help
